//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recursos.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar links.
        /// </summary>
        public static string AdicionarLinks {
            get {
                return ResourceManager.GetString("AdicionarLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ADMINISTRADOR.
        /// </summary>
        public static string ADMINISTRADOR {
            get {
                return ResourceManager.GetString("ADMINISTRADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ALTO.
        /// </summary>
        public static string ALTO {
            get {
                return ResourceManager.GetString("ALTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associação desfeita com sucesso!.
        /// </summary>
        public static string AssociaçãoDesfeita {
            get {
                return ResourceManager.GetString("AssociaçãoDesfeita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associação feita com sucesso, clique em salvar para armazenar os dados!.
        /// </summary>
        public static string AssociacaoFeitaSucesso {
            get {
                return ResourceManager.GetString("AssociacaoFeitaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associação realizada com sucesso!.
        /// </summary>
        public static string AssociacaoRealizada {
            get {
                return ResourceManager.GetString("AssociacaoRealizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associar.
        /// </summary>
        public static string Associar {
            get {
                return ResourceManager.GetString("Associar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associar links aos grupos.
        /// </summary>
        public static string AssociarLinks {
            get {
                return ResourceManager.GetString("AssociarLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associar usuários aos grupos.
        /// </summary>
        public static string AssociarUsuario {
            get {
                return ResourceManager.GetString("AssociarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativo.
        /// </summary>
        public static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        public static string Bairro {
            get {
                return ResourceManager.GetString("Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Bairro é Obrigatório!.
        /// </summary>
        public static string BairroObrigatório {
            get {
                return ResourceManager.GetString("BairroObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem vindo(a).
        /// </summary>
        public static string BemVindo {
            get {
                return ResourceManager.GetString("BemVindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BU.
        /// </summary>
        public static string BU {
            get {
                return ResourceManager.GetString("BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buscar por:.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Usuário.
        /// </summary>
        public static string CadastrarUsuario {
            get {
                return ResourceManager.GetString("CadastrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Menus.
        /// </summary>
        public static string CadastroMenus {
            get {
                return ResourceManager.GetString("CadastroMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Celular é Obrigatório!.
        /// </summary>
        public static string CelularObrigatório {
            get {
                return ResourceManager.GetString("CelularObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Centro de custo.
        /// </summary>
        public static string centroCusto {
            get {
                return ResourceManager.GetString("centroCusto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep.
        /// </summary>
        public static string Cep {
            get {
                return ResourceManager.GetString("Cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Cep é Obrigatório!.
        /// </summary>
        public static string CepObrigatório {
            get {
                return ResourceManager.GetString("CepObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        public static string Cidade {
            get {
                return ResourceManager.GetString("Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Cidade é Obrigatório!.
        /// </summary>
        public static string CidadeObrigatória {
            get {
                return ResourceManager.GetString("CidadeObrigatória", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique para adicioar filhos ao menu!.
        /// </summary>
        public static string CliqueAdicionarFilhos {
            get {
                return ResourceManager.GetString("CliqueAdicionarFilhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique para excluir!.
        /// </summary>
        public static string CliqueParaExcluir {
            get {
                return ResourceManager.GetString("CliqueParaExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a clique para pesquisar.
        /// </summary>
        public static string cliqueParaPesquisar {
            get {
                return ResourceManager.GetString("cliqueParaPesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código pai.
        /// </summary>
        public static string codigoPai {
            get {
                return ResourceManager.GetString("codigoPai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código Pai.
        /// </summary>
        public static string CódigoPai {
            get {
                return ResourceManager.GetString("CódigoPai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a como.
        /// </summary>
        public static string como {
            get {
                return ResourceManager.GetString("como", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CONTATO.
        /// </summary>
        public static string CONTATO {
            get {
                return ResourceManager.GetString("CONTATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CONTRASTE.
        /// </summary>
        public static string CONTRASTE {
            get {
                return ResourceManager.GetString("CONTRASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corpo.
        /// </summary>
        public static string Corpo {
            get {
                return ResourceManager.GetString("Corpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Corpo é Obrigatório!.
        /// </summary>
        public static string CorpoObrigatório {
            get {
                return ResourceManager.GetString("CorpoObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        public static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo CPF é Obrigatório!.
        /// </summary>
        public static string CPFObrigatório {
            get {
                return ResourceManager.GetString("CPFObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criar Grupo.
        /// </summary>
        public static string CriarGrupo {
            get {
                return ResourceManager.GetString("CriarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criar Postagem.
        /// </summary>
        public static string CriarPostagem {
            get {
                return ResourceManager.GetString("CriarPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Currículo.
        /// </summary>
        public static string Curriculo {
            get {
                return ResourceManager.GetString("Curriculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data final:.
        /// </summary>
        public static string DataFinal {
            get {
                return ResourceManager.GetString("DataFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data inicial:.
        /// </summary>
        public static string DataInicial {
            get {
                return ResourceManager.GetString("DataInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Data é Obrigatório!.
        /// </summary>
        public static string DataObrigatória {
            get {
                return ResourceManager.GetString("DataObrigatória", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desassociar os links dos grupos.
        /// </summary>
        public static string DesassociarLinks {
            get {
                return ResourceManager.GetString("DesassociarLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desativar/Ativar usuários.
        /// </summary>
        public static string DesativarAtivar {
            get {
                return ResourceManager.GetString("DesativarAtivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenvolvido.
        /// </summary>
        public static string Desenvolvido {
            get {
                return ResourceManager.GetString("Desenvolvido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhes.
        /// </summary>
        public static string Detalhes {
            get {
                return ResourceManager.GetString("Detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Menu.
        /// </summary>
        public static string EditarMenu {
            get {
                return ResourceManager.GetString("EditarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Rascunho.
        /// </summary>
        public static string EditarRascunho {
            get {
                return ResourceManager.GetString("EditarRascunho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É filho!.
        /// </summary>
        public static string ÉFilho {
            get {
                return ResourceManager.GetString("ÉFilho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Email é Obrigatório!.
        /// </summary>
        public static string EmailObrigatório {
            get {
                return ResourceManager.GetString("EmailObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua José Palma Rennó, 236
        ///                Centro | Santa Rita do Sapucaí
        ///                CEP 37540-000
        ///                Fone: 55 35 3473.3085.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENTRAR.
        /// </summary>
        public static string ENTRAR {
            get {
                return ResourceManager.GetString("ENTRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enviar.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enviar Imagem(s).
        /// </summary>
        public static string EnviarImagens {
            get {
                return ResourceManager.GetString("EnviarImagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro campos nome e/ou URL vazios!!.
        /// </summary>
        public static string ErroCampo {
            get {
                return ResourceManager.GetString("ErroCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro: Não foi associado nenhum Link!.
        /// </summary>
        public static string ErroLink {
            get {
                return ResourceManager.GetString("ErroLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha o usuário.
        /// </summary>
        public static string EscolhaUsuario {
            get {
                return ResourceManager.GetString("EscolhaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado civil.
        /// </summary>
        public static string EstadoCivil {
            get {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Etiqueta/Tags.
        /// </summary>
        public static string Etiqueta {
            get {
                return ResourceManager.GetString("Etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Etiqueta é Obrigatório!.
        /// </summary>
        public static string EtiquetaObrigatório {
            get {
                return ResourceManager.GetString("EtiquetaObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filhos.
        /// </summary>
        public static string Filhos {
            get {
                return ResourceManager.GetString("Filhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fone.
        /// </summary>
        public static string Fone {
            get {
                return ResourceManager.GetString("Fone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Fone é Obrigatório!.
        /// </summary>
        public static string FoneObrigatório {
            get {
                return ResourceManager.GetString("FoneObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a genero.
        /// </summary>
        public static string genero {
            get {
                return ResourceManager.GetString("genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gráfico.
        /// </summary>
        public static string grafico {
            get {
                return ResourceManager.GetString("grafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Gráfico é Obrigatório!.
        /// </summary>
        public static string graficoObrigatório {
            get {
                return ResourceManager.GetString("graficoObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gráfico Produção.
        /// </summary>
        public static string GraficoProducao {
            get {
                return ResourceManager.GetString("GraficoProducao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo e Links.
        /// </summary>
        public static string GrupoELinks {
            get {
                return ResourceManager.GetString("GrupoELinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupos.
        /// </summary>
        public static string Grupos {
            get {
                return ResourceManager.GetString("Grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupos existentes.
        /// </summary>
        public static string GruposExistentes {
            get {
                return ResourceManager.GetString("GruposExistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HISTÓRIA.
        /// </summary>
        public static string HISTÓRIA {
            get {
                return ResourceManager.GetString("HISTÓRIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HOME.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imagem.
        /// </summary>
        public static string Imagem {
            get {
                return ResourceManager.GetString("Imagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imagens.
        /// </summary>
        public static string Imagens {
            get {
                return ResourceManager.GetString("Imagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique para alterar a linguagem para Ingles!.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Link excluído com sucesso!.
        /// </summary>
        public static string LinkExcluido {
            get {
                return ResourceManager.GetString("LinkExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Links Cadastrados.
        /// </summary>
        public static string LinksCadastrados {
            get {
                return ResourceManager.GetString("LinksCadastrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de filhos para o pai:.
        /// </summary>
        public static string ListaFilhos {
            get {
                return ResourceManager.GetString("ListaFilhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LOCALIZAÇÃO.
        /// </summary>
        public static string LOCALIZAÇÃO {
            get {
                return ResourceManager.GetString("LOCALIZAÇÃO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login de usuário.
        /// </summary>
        public static string LoginUsuario {
            get {
                return ResourceManager.GetString("LoginUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Marcar como rascunho.
        /// </summary>
        public static string Marcar {
            get {
                return ResourceManager.GetString("Marcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MARKETING.
        /// </summary>
        public static string MARKETING {
            get {
                return ResourceManager.GetString("MARKETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a mensagem.
        /// </summary>
        public static string mensagem {
            get {
                return ResourceManager.GetString("mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a mensg.
        /// </summary>
        public static string mensg {
            get {
                return ResourceManager.GetString("mensg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Msg.
        /// </summary>
        public static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Msg é Obrigatório!.
        /// </summary>
        public static string MsgObrigatório {
            get {
                return ResourceManager.GetString("MsgObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a nascimento.
        /// </summary>
        public static string Nascimento {
            get {
                return ResourceManager.GetString("Nascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acesso Negado.
        /// </summary>
        public static string Negado {
            get {
                return ResourceManager.GetString("Negado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum link selecionado, favor selecionr ao menos um para editar o menu! .
        /// </summary>
        public static string NenhumLink {
            get {
                return ResourceManager.GetString("NenhumLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome é obrigatório! Será o nome que irá aparecer ao usuário!.
        /// </summary>
        public static string NomeObrigatório {
            get {
                return ResourceManager.GetString("NomeObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Número é Obrigatório!.
        /// </summary>
        public static string NumeroObrigatório {
            get {
                return ResourceManager.GetString("NumeroObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordem.
        /// </summary>
        public static string ordem {
            get {
                return ResourceManager.GetString("ordem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pai.
        /// </summary>
        public static string pai {
            get {
                return ResourceManager.GetString("pai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pelos.
        /// </summary>
        public static string pelos {
            get {
                return ResourceManager.GetString("pelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem permissão para acessar esse recurso....
        /// </summary>
        public static string Permissao {
            get {
                return ResourceManager.GetString("Permissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisar por data.
        /// </summary>
        public static string PesquisarPorData {
            get {
                return ResourceManager.GetString("PesquisarPorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite o título da postagem para pesquisar: .
        /// </summary>
        public static string PesquisarPorTítulo {
            get {
                return ResourceManager.GetString("PesquisarPorTítulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite o título do rascunho para pesquisar:.
        /// </summary>
        public static string PesquisarPorTítuloRascunho {
            get {
                return ResourceManager.GetString("PesquisarPorTítuloRascunho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisar por título.
        /// </summary>
        public static string PesquisarTítulo {
            get {
                return ResourceManager.GetString("PesquisarTítulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique para alterar a linguagem para Português!.
        /// </summary>
        public static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Postagens Cadastradas.
        /// </summary>
        public static string PostagensCadastradas {
            get {
                return ResourceManager.GetString("PostagensCadastradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Principal.
        /// </summary>
        public static string Principal {
            get {
                return ResourceManager.GetString("Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Privilégios é Obrigatório!.
        /// </summary>
        public static string PrivilegioObrigatório {
            get {
                return ResourceManager.GetString("PrivilegioObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Privilégios.
        /// </summary>
        public static string Privilegios {
            get {
                return ResourceManager.GetString("Privilegios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PROCESSOS.
        /// </summary>
        public static string PROCESSOS {
            get {
                return ResourceManager.GetString("PROCESSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PRODUÇÃO.
        /// </summary>
        public static string PRODUCAO {
            get {
                return ResourceManager.GetString("PRODUCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a QUALIDADE.
        /// </summary>
        public static string QUALIDADE {
            get {
                return ResourceManager.GetString("QUALIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a rascunho.
        /// </summary>
        public static string rascunho {
            get {
                return ResourceManager.GetString("rascunho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rascunhos Cadastrados.
        /// </summary>
        public static string Rascunhos {
            get {
                return ResourceManager.GetString("Rascunhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RECURSOSHUMANOS.
        /// </summary>
        public static string RECURSOSHUMANOS {
            get {
                return ResourceManager.GetString("RECURSOSHUMANOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remuneração.
        /// </summary>
        public static string Remuneracao {
            get {
                return ResourceManager.GetString("Remuneracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Remuneração é Obrigatório!.
        /// </summary>
        public static string remuneracaoObrigatória {
            get {
                return ResourceManager.GetString("remuneracaoObrigatória", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua.
        /// </summary>
        public static string Rua {
            get {
                return ResourceManager.GetString("Rua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Rua é Obrigatório!.
        /// </summary>
        public static string RuaObrigatória {
            get {
                return ResourceManager.GetString("RuaObrigatória", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvo com Sucesso!.
        /// </summary>
        public static string SalvoSucesso {
            get {
                return ResourceManager.GetString("SalvoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um grupo.
        /// </summary>
        public static string Selecioneumgrupo {
            get {
                return ResourceManager.GetString("Selecioneumgrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setor.
        /// </summary>
        public static string Setor {
            get {
                return ResourceManager.GetString("Setor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Situação.
        /// </summary>
        public static string situacao {
            get {
                return ResourceManager.GetString("situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Skype.
        /// </summary>
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TECNOLOGIA.
        /// </summary>
        public static string TECNOLOGIA {
            get {
                return ResourceManager.GetString("TECNOLOGIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefonef celular.
        /// </summary>
        public static string Telefonecelular {
            get {
                return ResourceManager.GetString("Telefonecelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone fixo.
        /// </summary>
        public static string Telefonefixo {
            get {
                return ResourceManager.GetString("Telefonefixo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fênix Indústria de Eletrônicos, fundada em 2010, é uma empresa multinacional de grande porte pertencente
        ///                                    ao grupo Foxconn, fundado em 1974, em Taiwan, com um investimento de US$ 7.500 milhões de dólares.
        ///                                    Hoje, o grupo é o maior exportador chinês e o segundo maior da República Tcheca. No Brasil.
        ///                                    a Fênix mantém sua sede em Santa Rita do Sapucaí, no estado de Minas Gerais, cidade que se tornou um dos
        ///    [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Texto1 {
            get {
                return ResourceManager.GetString("Texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A empresa oferece dois formatos de Gerenciamento de Materiais para melhor atender as
        ///                                            necessidades dos clientes.
        ///
        ///                                           Turn Key: A Fênix realiza a completa gestão dos materiais desde a aquisição, passando pelo
        ///                                            processo produtivo até a entrega do produto final ao cliente. Também é possível oferecer os serviços
        ///                                            de sourcing/consolidação dos mat [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Texto2 {
            get {
                return ResourceManager.GetString("Texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Equipamentos de alta Tecnologia, proporcionando maior produtividade com eficiência e qualidade;.
        /// </summary>
        public static string Texto3a {
            get {
                return ResourceManager.GetString("Texto3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Especialistas em Integrar Processos de Alta complexidade;.
        /// </summary>
        public static string Texto3b {
            get {
                return ResourceManager.GetString("Texto3b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Equipe de desenvolvimento voltada para a criação de processos produtivos, automatização e controle;.
        /// </summary>
        public static string Texto3c {
            get {
                return ResourceManager.GetString("Texto3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capacidade de Montagem de qualquer placa via tecnologia SMT e PTH;.
        /// </summary>
        public static string Texto3d {
            get {
                return ResourceManager.GetString("Texto3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linhas de Montagem controladas por um moderno sistema de rastreabilidade..
        /// </summary>
        public static string Texto3e {
            get {
                return ResourceManager.GetString("Texto3e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Como grande prioridade, a empresa Fênix implementa e adequa seus sistemas internos,
        ///                                    garantindo o amplo controle de qualidade em todos os processos realizados em sua planta produtiva..
        /// </summary>
        public static string Texto4 {
            get {
                return ResourceManager.GetString("Texto4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a • Controle ESD.
        /// </summary>
        public static string Texto5a {
            get {
                return ResourceManager.GetString("Texto5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a • Controle MSD.
        /// </summary>
        public static string Texto5b {
            get {
                return ResourceManager.GetString("Texto5b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a • Sistema de Gestão Integrada.
        /// </summary>
        public static string Texto5c {
            get {
                return ResourceManager.GetString("Texto5c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a • Inspeção de Recebimento.
        /// </summary>
        public static string Texto5d {
            get {
                return ResourceManager.GetString("Texto5d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a • Qualificação de fornecedores.
        /// </summary>
        public static string Texto5e {
            get {
                return ResourceManager.GetString("Texto5e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a • Equipamentos modernos para qualificação de produtos.
        /// </summary>
        public static string Texto5f {
            get {
                return ResourceManager.GetString("Texto5f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a • Controle estatístico de processos • Gestão Ambiental..
        /// </summary>
        public static string Texto5g {
            get {
                return ResourceManager.GetString("Texto5g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Com uma localização geográfica privilegiada, em uma das regiões que mais se desenvolve no país,
        ///                                    a Fênix está entre os três maiores centros econômicos e comerciais do Brasil, São Paulo, Rio de Janeiro
        ///                                    e Belo Horizonte, e às margens das principais rodovias do Sudeste..
        /// </summary>
        public static string Texto6 {
            get {
                return ResourceManager.GetString("Texto6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FOXCONN EM MINAS GERAIS BRASIL.
        /// </summary>
        public static string Titulo1 {
            get {
                return ResourceManager.GetString("Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PROCESSOS OFERECIDOS.
        /// </summary>
        public static string Titulo2 {
            get {
                return ResourceManager.GetString("Titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TECNOLOGIA INOVADORA.
        /// </summary>
        public static string Titulo3 {
            get {
                return ResourceManager.GetString("Titulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SISTEMA DE GESTÃO DA QUALIDADE.
        /// </summary>
        public static string Titulo4 {
            get {
                return ResourceManager.GetString("Titulo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LOCALIZAÇÃO ESTRATÉGICA.
        /// </summary>
        public static string Titulo5 {
            get {
                return ResourceManager.GetString("Titulo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Minas Gerais.
        /// </summary>
        public static string Titulo6 {
            get {
                return ResourceManager.GetString("Titulo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fale Conosco.
        /// </summary>
        public static string Titulo7 {
            get {
                return ResourceManager.GetString("Titulo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TRABALHE NA FÊNIX (LINK EXTERNO).
        /// </summary>
        public static string Titulo8 {
            get {
                return ResourceManager.GetString("Titulo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Título é Obrigatório!.
        /// </summary>
        public static string TituloObrigatório {
            get {
                return ResourceManager.GetString("TituloObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uf.
        /// </summary>
        public static string uf {
            get {
                return ResourceManager.GetString("uf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo UF é Obrigatório!.
        /// </summary>
        public static string UFObrigatório {
            get {
                return ResourceManager.GetString("UFObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Url do gráfico.
        /// </summary>
        public static string UrlGrafico {
            get {
                return ResourceManager.GetString("UrlGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Url é Obrigatória!.
        /// </summary>
        public static string URLObrigatória {
            get {
                return ResourceManager.GetString("URLObrigatória", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a URL salva com sucesso!.
        /// </summary>
        public static string URLSalva {
            get {
                return ResourceManager.GetString("URLSalva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique aqui para voltar.
        /// </summary>
        public static string Voltar {
            get {
                return ResourceManager.GetString("Voltar", resourceCulture);
            }
        }
    }
}
